import { ApiProperty } from '@nestjs/swagger';

export class ReadProductAdvertDto {
  @ApiProperty({ example: 1, description: 'ID of the advert' })
  id: number;

  @ApiProperty({ example: 15, description: 'Product ID' })
  productId: number | null;

  @ApiProperty({
    example: 123456789,
    description: 'OLX listing ID',
    required: false,
  })
  olxId?: number | null;

  @ApiProperty({
    example: 'Amazing Laptop',
    description: 'Title of the advertisement',
  })
  title: string;

  @ApiProperty({
    example: 'A powerful laptop with excellent battery life.',
    description: 'Description of the advertisement',
  })
  description: string;

  @ApiProperty({
    example: false,
    description: 'Indicates if the description was generated by AI',
  })
  isDescriptionGenerated: boolean;
}
